---
title: 'General Cubic Curve: Inflection Point and Symmetry'
subtitle: 'Inflection Point and Symmetry'
author: Recle Etino Vibal
date: '2018-10-12'
slug: general-cubic-curve-inflection-point-and-symmetry
categories:
  - Calculus
  - Mathematics
  - Mathjax
tags:
  - derivatives
  - maxima
  - minima
  - inflection point
  - symmetry
  - cubic equation
  - quadratic equation
description: ''
output:
  blogdown::html_page:
    toc: yes
    number_sections: true
bibliography:
  - references/cwag2016.bib
biblio-style: apalike
---

# Problem

Problem 40, page 157 in @cwag2016

Consider the general cubic equation 

$$
\begin{equation}
y = a x^3 + b x^2 + c x + d
(\#eq:general-cubic)
\end{equation}
$$

Show that:

1. It has one and only one point of inflection at $I (\frac{-b}{3a}, k)$ where $k = \frac{2 b^3}{27 a^2} - \frac{bc}{3a} + d$,
2. It has one maximum point and one minimum point if and only if $b^2 - 3ac \gt 0$,
3. The abscissa of $I$ is the average of the abscissas of the maximum and minimum point, and
4. The curve is symmetric with respect to $I$ by
    a. Introducing a new $X$-axis and $Y$-axis such that $X = x + \frac{b}{3a}$ and $Y = y - k$ and making $I$ as the origin of the $XY$-system,
    b. Showing that the equation of the curve in the $XY$-system is $Y = aX \left(X^2 - \frac{b^2 - 3ac}{3 a^2} \right)$, and
    c. Showing that this transformed equation is symmetric with respect to $I$.
  
# Solution

## Inflection Point

The inflection point, at which the curve changes its concavity, of a curve can be determined by finding the root of the second derivative ($f'' \left( x \right) = 0$).

Computing for the second derivative of \@ref(eq:general-cubic),

$$
\begin{align}
y &= f \left( x \right) = a x^3 + b x^2 + c x + d
\\
\\
f' \left( x \right) &= 3a x^2 + 2b x + c (\#eq:first-derivative)
\\
\\
f'' \left(x \right) &= 6a x + 2b (\#eq:second-derivative)
\end{align}
$$

Finding the roots of \@ref(eq:second-derivative),

$$
\begin{align}
6a x + 2b &= 0
\\
6a x &= -2b
\\
x &= \frac{-2b}{6a}
\\
x &= \frac{-b}{3a} (\#eq:abscissa-inflection)
\end{align}
$$

To find the ordinate of the point of inflection, substitute \@ref(eq:abscissa-inflection) to the \@ref(eq:general-cubic)

$$
\begin{align}
y &= a \left( \frac{-b}{3a} \right)^3 + b \left( \frac{-b}{3a} \right)^2 + c \left( \frac{-b}{3a} \right) + d
\\
\\
y &= a \left( \frac{-b^3}{27 a^3} \right) + b \left( \frac{b^2}{9 a^2} \right) + \left( \frac{-bc}{3a} \right) + d
\\
\\
y &= \frac{-b^3}{27 a^2} + \frac{b^3}{9 a^2} - \frac{bc}{3a} + d
\\
\\
y &= \frac{-b^3 + 3 b^3}{27 a^2} - \frac{bc}{3a} + d
\\
\\
y &= \frac{2 b^3}{27 a^2} - \frac{bc}{3a} + d (\#eq:ordinate-inflection)
\end{align}
$$

This proves that the one and only point of inflection of \@ref(eq:general-cubic) is at $I (\frac{-b}{3a}, \frac{2 b^3}{27 a^2} - \frac{bc}{3a} + d)$.

## Maxima and Minima

The extremas of a curve can be determined by finding the roots of the first derivative. 

Equating \@ref(eq:first-derivative) to zero,

$$
\begin{equation}
3a x^2 + 2b x + c = 0
(\#eq:zero-first-derivative)
\end{equation}
$$

Before we solve \@ref(eq:zero-frist-derivative), I think this is a good opportunity to review the quadratic formula. Given a generalized quadratic equation

$$
\begin{equation}
a x^2 + b x + c = 0
(\#eq:quadratic)
\end{equation}
$$

We can solve the roots of \@ref(eq:quadratic) with the quadratic formula

$$
\begin{equation}
x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
(\#eq:quadratic-formula)
\end{equation}
$$

The roots of \@ref(eq:zero-first-derivative) can be calculated using \@ref(eq:quadratic-formula). However, we must be mindful of our coefficients.

$$
\begin{align}
x &= \frac{-2b \pm \sqrt{\left( 2b \right)^2 - 4 \left( 3a \right) c}}{2 \left( 3a \right)}
\\
\\
&= \frac{-2b \pm \sqrt{4b^2 - 12a c}}{6a}
\\
\\
&= \frac{-2b \pm 2 \sqrt{b^2 - 3a c}}{6a}
\\
\\
x &= \frac{-b \pm \sqrt{b^2 - 3a c}}{3a}
\\
\\
x_{min} &= \frac{-b - \sqrt{b^2 - 3a c}}{3a} (\#eq:minimum-cubic)
\\
\\
x_{max} &= \frac{-b - \sqrt{b^2 - 3a c}}{3a} (\#eq:maximum-cubic)
\end{align}
$$

Note that \@ref(eq:minimum-cubic) and \@ref(eq:maximum-cubic) will only exist if $b^2 - 3ac \gt 0$.


# Reference

Problems and lessons from
