---
title: Sine, Cosine, and Multiples of Angles
author: Recle Etino Vibal
date: '2018-10-17'
slug: sine-cosine-multiples-angles
categories:
  - Mathematics
  - trigonometry
  - Mathjax
tags:
  - sine
  - cosine
  - trigonometric identites
output:
  blogdown::html_page:
    toc: yes
    number_sections: yes
bibliography:
  - references/cwag2016.bib
biblio-style: apalike
---

# Review of Trigonometric Identities

Here is an overview of some of the most important trigonometric identites. In my opinion, one can derive other trigonometric identities just by knowing these.

$$
\begin{align}
\sin \left( - \theta \right) &= - \sin \theta (\#eq:sine-negative)
\\
\\
\cos \left( - \theta \right) &= \cos \theta (\#eq:cosine-negative)
\\
\\
\sin^2 \theta + \cos^2 \theta &= 1 (\#eq:pythagorean)
\\
\\
\sin \left(  \theta + \phi \right) &= \sin \theta \sin \phi + \cos \theta \sin \phi (\#eq:sum-sine)
\\
\\
\cos \left( \theta + \phi \right) &= \cos \theta \cos \phi - \sin \theta \sin \phi (\#eq:sum-cosine)
\end{align}
$$

A special identity for equations \@ref(eq:sum-sine) and \@ref(eq:sum-cosine) happens when $\theta = \phi$.

$$
\begin{align}
\sin \left( 2 \theta \right) &= 2 \sin \theta \cos \theta (\#eq:double-angle-sine)
\\
\\
\cos \left( 2 \theta \right) &= \cos^2 \theta - \sin^2 \theta (\#eq:double-angle-cosine)
\end{align}
$$

# Problems

## Quadruple Angle

Problem 62, page 50 in @cwag2016.

Verify:

$$
\begin{align}
\sin 4 \theta &= 8 \sin \theta \cos^3 \theta - 4 \sin \theta \cos \theta (\#eq:problem-quad-sine)
\\
\\
\cos 4 \theta &= 8 \cos^4 \theta - 8 \cos^2 \theta + 1 (\#eq:problem-quad-cosine)
\end{align}
$$

## Multiple Angles Sine and Cosine Product

Problem 63, page 50 in @cwag2016.

Prove:

$$
\begin{align}
\sin m \theta \sin n \theta &= \frac{1}{2} \left[ \cos \left( m - n \right) \theta - \cos \left( m + n \right) \theta \right] (\#eq:problem-sine-sine)
\\
\\
\sin m \theta \cos n \theta &= \frac{1}{2} \left[ \sin \left( m + n \right) \theta - \sin \left( m - n \right) \theta \right] (\#eq:problem-sine-cosine)
\\
\\
\cos m \theta \cos n \theta &= \frac{1}{2} \left[ \cos \left( m + n \right) \theta + \cos \left( m - n \right) \theta \right] (\#eq:problem-cosine-cosine)
\end{align}
$$

# Solutions

## Quadruple is Double Double

Problems \@ref(eq:problem-quad-sine) and \@ref(eq:problem-quad-cosine) can be solved using identities \@ref(eq:double-angle-sine), \@ref(eq:double-angle-cosine), and \@ref(eq:pythagorean).

$$
\begin{align}
\sin 4 \theta &= \sin 2 \left( 2 \theta \right)
\\
&= 2 \sin 2 \theta \cos 2 \theta
\\
&= 2 \left( 2 \sin \theta \cos \theta \right) \left( \cos^2 \theta - \sin^2 \theta \right)
\\
&= 4 \sin \theta \cos \theta \left[ \cos^2 \theta - \left( 1 - \cos^2 \theta \right) \right]
\\
&= 4 \sin \theta \cos^3 \theta - 4 \sin \theta \cos \theta + 4 \sin \theta \cos^3 \theta
\\
\sin 4 \theta &= 8 \sin \theta \cos^3 \theta - 4 \sin \theta \cos \theta
\\
\\
\cos 4 \theta &= \cos 2 \left( 2 \theta \right)
\\
&= \cos^2 2 \theta - \sin^2 2 \theta
\\
&= \cos^2 2 \theta - \left( 1 - \cos^2 2 \theta \right)
\\
&= 2 \cos^2 2 \theta - 1
\\
&= 2 \left( \cos 2 \theta \right)^2 - 1
\\
&= 2 \left( \cos^2 \theta - \sin^2 \theta \right)^2 - 1
\\
&= 2 (\cos^4 \theta - 2 cos^2 \theta \sin^2 \theta + \sin^4 \theta) - 1
\\
&= 2 \left( \cos^4 \theta - 2 cos^2 \theta \sin^2 \theta + \sin^4 \theta \right) - 1
\\
&= 2 \left[ \cos^4 \theta - 2 cos^2 \theta \left( 1 - \cos^2 \theta \right) + \left( 1 - \cos^2 \theta \right)^2 \right] - 1
\\
&= 2 \left( \cos^4 \theta - 2 cos^2 \theta + 2 \cos^4 \theta + 1 - 2 \cos^2 \theta + \cos^4 \theta \right) - 1
\\
&= 2 \left( 4 \cos^4 \theta - 4 cos^2 \theta + 1 \right) - 1
\\
&= 8 \cos^4 \theta - 8 cos^2 \theta + 2 - 1
\\
\cos 4 \theta &= 8 \cos^4 \theta - 8 cos^2 \theta + 1
\end{align}
$$

## Add and Subtract

Problems \@ref(eq:problem-sine-sine), \@ref(eq:problem-sine-cosine), and \@ref(eq:problem-cosine-cosine) already offer clues on the proofs' process. The left hand side of the equations can be seen in identities \@ref(eq:sum-sine) and \@ref(eq:sum-cosine). We will also need identities \@ref(eq:sine-negative) and \@ref(eq:cosine-negative) to simplify the sine and cosine of the negative angles.

$$
\begin{align}
\cos \left( m + n \right) \theta &= \cos \left( m \theta + n \theta \right)
\\
\cos \left( m + n \right) \theta &= \cos m \theta \cos n \theta - \sin m \theta \sin n \theta (\#eq:cosine-m-plus-n)
\\
\\
\cos \left( m - n \right) \theta &= \cos \left( m \theta - n \theta \right)
\\
&= \cos m \theta \cos \left( - n \theta \right) - \sin m \theta \sin \left( - n \theta \right)
\\
\cos \left( m - n \right) \theta &= \cos m \theta \cos n \theta + \sin m \theta \sin n \theta (\#eq:cosine-m-minus-n)
\\
\\
\sin \left(m + n \right) \theta &= \sin \left( m \theta + n \theta \right)
\\
\sin \left(m + n \right) \theta &= \sin m \theta \cos n \theta + \cos m \theta \sin n \theta (\#eq:sine-m-plus-n)
\\
\\
\sin \left(m - n \right) \theta &= \sin \left( m \theta - n \theta \right)
\\
&= \sin m \theta \cos \left( - n \theta \right) + \cos m \theta \sin \left( - n \theta \right)
\\
\sin \left(m - n \right) \theta &= \sin m \theta \cos n \theta - \cos m \theta \sin n \theta (\#eq:sine-m-minus-n)
\end{align}
$$

We derive \@ref(eq:problem-sine-sine) by subtracting \@ref(eq:cosine-m-minus-n) from \@ref(eq:cosine-m-plus-n).

$$
\require{cancel}
\begin{align}
\cos \left( m + n \right) \theta - \cos \left( m - n \right) \theta &= \cos m \theta \cos n \theta - \sin m \theta \sin n \theta - \left( \cos m \theta \cos n \theta + \sin m \theta \sin n \theta \right)
\\
 &= \cancelto{0}{\cos m \theta \cos n \theta - \cos m \theta \cos n \theta} - \sin m \theta \sin n \theta- \sin m \theta \sin n \theta
 \\
\cos \left( m + n \right) \theta - \cos \left( m - n \right) \theta &= -2 sin m \theta \sin n \theta
\\
\sin m \theta \sin n \theta &= - \frac{1}{2} \left[ \cos \left( m + n \right) \theta - \cos \left( m - n \right) \theta \right]
\\
\sin m \theta \sin n \theta &= \frac{1}{2} \left[ \cos \left( m - n \right) \theta - \cos \left( m + n \right) \theta \right]
\end{align}
$$

Problem \@ref(eq:problem-sine-cosine) by adding \@ref(eq:sine-m-plus-n) and \@ref(eq:sine-m-minus-n).

$$
\begin{align}
\sin \left(m + n \right) \theta + \sin \left(m - n \right) \theta &= \sin m \theta \cos n \theta + \cos m \theta \sin n \theta + \left( \sin m \theta \cos n \theta - \cos m \theta \sin n \theta \right)
\\
&= \sin m \theta \cos n \theta + \sin m \theta \cos n \theta + \cancelto{0}{\cos m \theta \sin n \theta - \cos m \theta \sin n \theta}
\\
\sin \left(m + n \right) \theta + \sin \left(m - n \right) \theta &= 2 \sin m \theta \cos n \theta
\\
\sin m \theta \cos n \theta &= \frac{1}{2} \left[ \sin \left(m + n \right) \theta + \sin \left(m - n \right) \theta \right]
\end{align}
$$

Finally, we can derive problem \@ref(eq:problem-cosine-cosine) by adding \@ref(eq:cosine-m-plus-n) and \@ref(eq:cosine-m-minus-n).

$$
\begin{align}
\cos \left( m + n \right) \theta + \cos \left( m - n \right) \theta &= \cos m \theta \cos n \theta - \sin m \theta \sin n \theta + \cos m \theta \cos n \theta + \sin m \theta \sin n \theta
\\
&= \cos m \theta \cos n \theta + \cos m \theta \cos n \theta \cancelto{0}{- \sin m \theta \sin n \theta + \sin m \theta \sin n \theta}
\\
\cos \left( m + n \right) \theta + \cos \left( m - n \right) \theta &= 2 \cos m \theta \cos n \theta
\\
\cos m \theta \cos n \theta &= \frac{1}{2} \left[ \cos \left( m + n \right) \theta + \cos \left( m - n \right) \theta \right]
\end{align}
$$

# Reference

Lessons and problems from
